apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 4
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: quicktrips-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000