"""users table

Revision ID: 458c3e08f7fe
Revises: 
Create Date: 2019-12-07 22:33:03.778930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458c3e08f7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cityname', sa.String(length=64), nullable=True),
    sa.Column('countryname', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_cityname'), 'recommendation', ['cityname'], unique=True)
    op.create_index(op.f('ix_recommendation_countryname'), 'recommendation', ['countryname'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_recommendation_countryname'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_cityname'), table_name='recommendation')
    op.drop_table('recommendation')
    # ### end Alembic commands ###
