"""adding more user fields

Revision ID: 63662f3c5fe9
Revises: 7cfb5c0b56ae
Create Date: 2020-01-12 10:28:26.753349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63662f3c5fe9'
down_revision = '7cfb5c0b56ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_postcode'), 'user', ['postcode'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_postcode'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
