"""more recommendation fields

Revision ID: 7145135cd62d
Revises: 63662f3c5fe9
Create Date: 2020-01-14 10:11:42.555516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7145135cd62d'
down_revision = '63662f3c5fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('description', sa.String(length=400), nullable=True))
    op.add_column('recommendation', sa.Column('flight', sa.String(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'hotel')
    op.drop_column('recommendation', 'flight')
    op.drop_column('recommendation', 'description')
    # ### end Alembic commands ###
