"""empty message

Revision ID: 0b4ebc1029c5
Revises: 17035dc67cd6
Create Date: 2020-03-28 18:17:49.900893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4ebc1029c5'
down_revision = '17035dc67cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=400), nullable=True),
    sa.Column('maxbudget', sa.String(length=400), nullable=True),
    sa.Column('minbudget', sa.String(length=400), nullable=True),
    sa.Column('adults', sa.String(length=400), nullable=True),
    sa.Column('children6', sa.String(length=400), nullable=True),
    sa.Column('children612', sa.String(length=400), nullable=True),
    sa.Column('children1218', sa.String(length=400), nullable=True),
    sa.Column('startdate', sa.String(length=400), nullable=True),
    sa.Column('enddate', sa.String(length=400), nullable=True),
    sa.Column('localorabroad', sa.String(length=400), nullable=True),
    sa.Column('origincountry', sa.String(length=400), nullable=True),
    sa.Column('originstate', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index('ix_favourite_city')
        batch_op.create_index(batch_op.f('ix_favourite_city'), ['city'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_city'))
        batch_op.create_index('ix_favourite_city', ['city'], unique=1)

    op.drop_table('current_questionnaire')
    # ### end Alembic commands ###
