"""empty message

Revision ID: 1d1426b47ac9
Revises: 6dc2d63b5168
Create Date: 2020-03-24 07:01:42.709297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1426b47ac9'
down_revision = '6dc2d63b5168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_column('key_attraction')
        batch_op.drop_column('flight3')
        batch_op.drop_column('flight1')
        batch_op.drop_column('country')
        batch_op.drop_column('hotel1')
        batch_op.drop_column('hotel2')
        batch_op.drop_column('flight2')
        batch_op.drop_column('hotel3')

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('key_attraction')
        batch_op.drop_column('flight3')
        batch_op.drop_column('county')
        batch_op.drop_column('flight1')
        batch_op.drop_column('country')
        batch_op.drop_column('hotel1')
        batch_op.drop_column('hotel2')
        batch_op.drop_column('flight2')
        batch_op.drop_column('hotel3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel3', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight2', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('hotel2', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('hotel1', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight1', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('county', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight3', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('key_attraction', sa.VARCHAR(length=140), nullable=True))

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel3', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight2', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('hotel2', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('hotel1', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight1', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('flight3', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('key_attraction', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
