"""delete table

Revision ID: 29b64fa26046
Revises: ecef100e2809
Create Date: 2020-03-03 21:29:12.653799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b64fa26046'
down_revision = 'ecef100e2809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.VARCHAR(length=140), nullable=False),
    sa.Column('keywords', sa.BLOB(), nullable=True),
    sa.Column('sentiment', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###
