"""empty message

Revision ID: 2d88ac8a9bee
Revises: 2d2c9b6a884a
Create Date: 2020-03-23 18:06:52.676191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d88ac8a9bee'
down_revision = '2d2c9b6a884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('region', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###
