"""adding country column

Revision ID: 44cfca1a57fa
Revises: 5a76e1e601f0
Create Date: 2020-03-03 21:31:23.613806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cfca1a57fa'
down_revision = '5a76e1e601f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_city', sa.Column('country', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_city', 'country')
    # ### end Alembic commands ###
