"""empty message

Revision ID: 486cae8da57f
Revises: 7c1bc876e985
Create Date: 2020-03-24 00:25:27.139197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486cae8da57f'
down_revision = '7c1bc876e985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.drop_column('recommendation', 'county')
    op.drop_column('recommendation', 'image')
    op.drop_column('recommendation', 'flight2')
    op.drop_column('recommendation', 'hotel3')
    op.drop_column('recommendation', 'hotel2')
    op.drop_column('recommendation', 'hotels')
    op.drop_column('recommendation', 'flights')
    op.drop_column('recommendation', 'keywords')
    op.drop_column('recommendation', 'user_id')
    op.drop_column('recommendation', 'flight1')
    op.drop_column('recommendation', 'description')
    op.drop_column('recommendation', 'country')
    op.drop_column('recommendation', 'flight3')
    op.drop_column('recommendation', 'hotel1')
    op.drop_column('recommendation', 'key_attraction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('key_attraction', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel1', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('flight3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('country', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('description', sa.VARCHAR(length=400), nullable=True))
    op.add_column('recommendation', sa.Column('flight1', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('recommendation', sa.Column('keywords', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('flights', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('hotels', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('hotel2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('flight2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('image', sa.VARCHAR(length=400), nullable=True))
    op.add_column('recommendation', sa.Column('county', sa.VARCHAR(length=140), nullable=True))
    op.create_foreign_key(None, 'recommendation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
