"""empty message

Revision ID: 4f3ca8f72b79
Revises: 5a1f7e8bfb11
Create Date: 2020-03-20 19:28:22.606331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3ca8f72b79'
down_revision = '5a1f7e8bfb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities_to_avoid',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_postcode'), 'user', ['postcode'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('hotel1', sa.String(length=140), nullable=True),
    sa.Column('flight1', sa.String(length=140), nullable=True),
    sa.Column('hotel2', sa.String(length=140), nullable=True),
    sa.Column('flight2', sa.String(length=140), nullable=True),
    sa.Column('hotel3', sa.String(length=140), nullable=True),
    sa.Column('flight3', sa.String(length=140), nullable=True),
    sa.Column('key_attraction', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('hotel1', sa.String(length=140), nullable=True),
    sa.Column('flight1', sa.String(length=140), nullable=True),
    sa.Column('hotel2', sa.String(length=140), nullable=True),
    sa.Column('flight2', sa.String(length=140), nullable=True),
    sa.Column('hotel3', sa.String(length=140), nullable=True),
    sa.Column('flight3', sa.String(length=140), nullable=True),
    sa.Column('key_attraction', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('county', sa.String(length=140), nullable=True),
    sa.Column('hotel1', sa.String(length=140), nullable=True),
    sa.Column('flight1', sa.String(length=140), nullable=True),
    sa.Column('hotel2', sa.String(length=140), nullable=True),
    sa.Column('flight2', sa.String(length=140), nullable=True),
    sa.Column('hotel3', sa.String(length=140), nullable=True),
    sa.Column('flight3', sa.String(length=140), nullable=True),
    sa.Column('key_attraction', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('past_trip')
    op.drop_table('favourite')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_postcode'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_table('processed_city')
    op.drop_table('cities_to_avoid')
    # ### end Alembic commands ###
