"""empty message

Revision ID: 50fabd40b7e6
Revises: 2d88ac8a9bee
Create Date: 2020-03-23 21:05:46.856094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fabd40b7e6'
down_revision = '2d88ac8a9bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('flights', sa.PickleType(), nullable=True))
    op.add_column('recommendation', sa.Column('hotels', sa.PickleType(), nullable=True))
    op.drop_column('recommendation', 'hotel1')
    op.drop_column('recommendation', 'flight3')
    op.drop_column('recommendation', 'hotel2')
    op.drop_column('recommendation', 'hotel3')
    op.drop_column('recommendation', 'flight1')
    op.drop_column('recommendation', 'flight2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('flight2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('flight1', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('flight3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('recommendation', sa.Column('hotel1', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('recommendation', 'hotels')
    op.drop_column('recommendation', 'flights')
    # ### end Alembic commands ###
