"""remove cities

Revision ID: 5a1f7e8bfb11
Revises: 6b993e9e933f
Create Date: 2020-03-14 07:06:23.323142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1f7e8bfb11'
down_revision = '6b993e9e933f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###
