"""update

Revision ID: 62782454ca0d
Revises: 611e27467c77
Create Date: 2020-03-11 15:40:05.820387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62782454ca0d'
down_revision = '611e27467c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.VARCHAR(length=140), nullable=False),
    sa.Column('country', sa.VARCHAR(length=140), nullable=True),
    sa.Column('keywords', sa.BLOB(), nullable=True),
    sa.Column('sentiment', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###
