"""recommendations table

Revision ID: 64fd9a43a1a2
Revises: 97ca74deb5a3
Create Date: 2020-02-26 12:25:38.476281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fd9a43a1a2'
down_revision = '97ca74deb5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('county', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'county')
    # ### end Alembic commands ###
