"""cities table

Revision ID: 711aefd9e05e
Revises: 721c2e56bb71
Create Date: 2020-03-03 10:03:05.988023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711aefd9e05e'
down_revision = '721c2e56bb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.VARCHAR(length=140), nullable=False),
    sa.Column('keywords', sa.BLOB(), nullable=True),
    sa.Column('sentiment', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###
