"""empty message

Revision ID: 7836f82c1942
Revises: 94d692b43dce
Create Date: 2020-03-23 14:50:05.127580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7836f82c1942'
down_revision = '94d692b43dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('region', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past_trip')
    # ### end Alembic commands ###
