"""new

Revision ID: 7dec66bea917
Revises: 
Create Date: 2020-04-02 23:58:50.559508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dec66bea917'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities_to_avoid',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('current_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=400), nullable=True),
    sa.Column('maxbudget', sa.String(length=400), nullable=True),
    sa.Column('minbudget', sa.String(length=400), nullable=True),
    sa.Column('adults', sa.String(length=400), nullable=True),
    sa.Column('children6', sa.String(length=400), nullable=True),
    sa.Column('children612', sa.String(length=400), nullable=True),
    sa.Column('children1218', sa.String(length=400), nullable=True),
    sa.Column('startdate', sa.String(length=400), nullable=True),
    sa.Column('enddate', sa.String(length=400), nullable=True),
    sa.Column('localorabroad', sa.String(length=400), nullable=True),
    sa.Column('origincountry', sa.String(length=400), nullable=True),
    sa.Column('originstate', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('region', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('shared_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_postcode'), 'user', ['postcode'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('past_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.Column('isFavourited', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_user')
    op.drop_table('_past_trip')
    op.drop_table('_current_recommendation')
    op.drop_table('_cities_to_avoid')
    op.drop_table('_recommendation')
    op.drop_table('_processed_city')
    op.drop_table('_current_questionnaire')
    op.drop_table('_shared_recommendations')
    op.drop_table('_alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=12), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_shared_recommendations',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=27), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=502), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('flights', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('hotels', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_current_questionnaire',
    sa.Column('id', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('maxbudget', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('minbudget', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('adults', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('children6', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('children612', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('children1218', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('startdate', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('enddate', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('localorabroad', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('origincountry', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('originstate', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_processed_city',
    sa.Column('city', sa.VARCHAR(length=34), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=32), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=41), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.NUMERIC(precision=9, scale=8), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=2441), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_recommendation',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=27), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=508), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('flights', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('hotels', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('isfavourited', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    op.create_table('_cities_to_avoid',
    sa.Column('city', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_current_recommendation',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=8), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1214), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('flights', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('hotels', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_past_trip',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=9), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    op.create_table('_user',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=26), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=7), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=5), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=19), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=15), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=5), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=94), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.drop_table('recommendation')
    op.drop_table('past_trip')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_postcode'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_table('shared_recommendations')
    op.drop_table('processed_city')
    op.drop_table('current_recommendation')
    op.drop_table('current_questionnaire')
    op.drop_table('cities_to_avoid')
    # ### end Alembic commands ###
