"""empty message

Revision ID: 88838de76bab
Revises: ed434981f5cc
Create Date: 2020-03-24 00:29:34.431988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88838de76bab'
down_revision = 'ed434981f5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('image', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
