"""empty message

Revision ID: 94b2039275a0
Revises: e9f308591882
Create Date: 2020-03-24 00:31:28.652563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b2039275a0'
down_revision = 'e9f308591882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('image', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
