"""adding processed city

Revision ID: 957b68112971
Revises: 44cfca1a57fa
Create Date: 2020-03-05 13:06:19.434703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957b68112971'
down_revision = '44cfca1a57fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.add_column('recommendation', sa.Column('county', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'county')
    op.drop_table('processed_city')
    # ### end Alembic commands ###
