"""empty message

Revision ID: a2f285069c1a
Revises: fbc05fd6722e
Create Date: 2020-03-24 09:34:11.291513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f285069c1a'
down_revision = 'fbc05fd6722e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
