"""empty message

Revision ID: a9e5470fee41
Revises: e09ba91eedc9
Create Date: 2020-03-31 17:23:36.642703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e5470fee41'
down_revision = 'e09ba91eedc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.drop_column('rating')

    op.drop_table('shared_recommendations')
    # ### end Alembic commands ###
