"""empty message

Revision ID: ad5caeb85005
Revises: a2f285069c1a
Create Date: 2020-03-30 11:14:46.964827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5caeb85005'
down_revision = 'a2f285069c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=400), nullable=True),
    sa.Column('maxbudget', sa.String(length=400), nullable=True),
    sa.Column('minbudget', sa.String(length=400), nullable=True),
    sa.Column('adults', sa.String(length=400), nullable=True),
    sa.Column('children6', sa.String(length=400), nullable=True),
    sa.Column('children612', sa.String(length=400), nullable=True),
    sa.Column('children1218', sa.String(length=400), nullable=True),
    sa.Column('startdate', sa.String(length=400), nullable=True),
    sa.Column('enddate', sa.String(length=400), nullable=True),
    sa.Column('localorabroad', sa.String(length=400), nullable=True),
    sa.Column('origincountry', sa.String(length=400), nullable=True),
    sa.Column('originstate', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_city'), ['city'], unique=False)
        batch_op.drop_column('image')

    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('processed_city', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=400), nullable=True))

    with op.batch_alter_table('processed_city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=140), nullable=True))

    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=140), nullable=True))

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_index(batch_op.f('ix_favourite_city'))

    op.drop_table('shared_recommendations')
    op.drop_table('current_recommendation')
    op.drop_table('current_questionnaire')
    # ### end Alembic commands ###
