"""update

Revision ID: b39494193589
Revises: 62782454ca0d
Create Date: 2020-03-11 15:40:26.950997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39494193589'
down_revision = '62782454ca0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_city',
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_city')
    # ### end Alembic commands ###
