"""empty message

Revision ID: d85a8a4159be
Revises: a9e5470fee41
Create Date: 2020-03-31 14:13:05.479769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85a8a4159be'
down_revision = 'a9e5470fee41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index('ix_favourite_city')

    op.drop_table('favourite')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isFavourited', sa.Boolean(create_constraint=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('isFavourited')

    op.create_table('favourite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=140), nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('flights', sa.BLOB(), nullable=True),
    sa.Column('hotels', sa.BLOB(), nullable=True),
    sa.Column('keywords', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index('ix_favourite_city', ['city'], unique=False)

    # ### end Alembic commands ###
