"""del

Revision ID: dccf66c8d49a
Revises: 0778c9228de7
Create Date: 2020-03-23 14:46:18.447699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccf66c8d49a'
down_revision = '0778c9228de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_trip', 'description')
    op.drop_column('past_trip', 'flight3')
    op.drop_column('past_trip', 'flight1')
    op.drop_column('past_trip', 'hotel1')
    op.drop_column('past_trip', 'flight2')
    op.drop_column('past_trip', 'hotel3')
    op.drop_column('past_trip', 'key_attraction')
    op.drop_column('past_trip', 'hotel2')
    op.add_column('recommendation', sa.Column('image', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'image')
    op.add_column('past_trip', sa.Column('hotel2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('key_attraction', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('hotel3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('flight2', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('hotel1', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('flight1', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('flight3', sa.VARCHAR(length=140), nullable=True))
    op.add_column('past_trip', sa.Column('description', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
