"""empty message

Revision ID: dcf5e5df85e0
Revises: f2447e7567d2
Create Date: 2020-03-23 14:59:49.702886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf5e5df85e0'
down_revision = 'f2447e7567d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_city', sa.Column('region', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_city', 'region')
    # ### end Alembic commands ###
