"""empty message

Revision ID: e09ba91eedc9
Revises: a2c19375ac71
Create Date: 2020-03-31 11:01:21.240113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09ba91eedc9'
down_revision = 'a2c19375ac71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trip', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
