"""empty message

Revision ID: e9f308591882
Revises: 88838de76bab
Create Date: 2020-03-24 00:30:42.910690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f308591882'
down_revision = '88838de76bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('image', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
