"""empty message

Revision ID: ed434981f5cc
Revises: 486cae8da57f
Create Date: 2020-03-24 00:27:01.257045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed434981f5cc'
down_revision = '486cae8da57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'image')
    op.drop_column('recommendation', 'flights')
    op.drop_column('recommendation', 'keywords')
    op.drop_column('recommendation', 'hotels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('hotels', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('keywords', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('flights', sa.BLOB(), nullable=True))
    op.add_column('recommendation', sa.Column('image', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
