"""empty message

Revision ID: f7d4fe5cf35e
Revises: a2f285069c1a
Create Date: 2020-03-26 11:39:58.600352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d4fe5cf35e'
down_revision = 'a2f285069c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('flights', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.PickleType(), nullable=True),
    sa.Column('hotels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_recommendation')
    # ### end Alembic commands ###
