"""add user hashcode

Revision ID: fac1eeeac8a8
Revises: d85a8a4159be
Create Date: 2020-04-04 02:02:17.905441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac1eeeac8a8'
down_revision = 'd85a8a4159be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashCode', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hashCode')

    # ### end Alembic commands ###
